name: ship
channels:
  - conda-forge
dependencies:
  - click
  - parcels >= 3, < 4
  - pyproj >= 3, < 4
  - sortedcontainers == 2.4.0
  - opensimplex == 0.4.5
  - numpy >=1, < 2
  - pydantic >=2, <3
  - pip

  # linting
  - pre-commit

  # Testing
  - pytest
  - pytest-cov
  - codecov
  - seabird
  - setuptools

  # Docs
  - sphinx>=7.0
  - myst-parser>=0.13
  - nbsphinx
  - ipykernel
  - pandoc
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - furo
  - sphinx-autobuild
