name: ship
channels:
  - conda-forge
dependencies:
  - click
  - parcels >3.1.0
  - pyproj >= 3, < 4
  - sortedcontainers == 2.4.0
  - opensimplex == 0.4.5
  - numpy >=1, < 2
  - pydantic >=2, <3
  - pip
  - pyyaml
  - copernicusmarine >= 2.2.2
  - openpyxl
  - yaspin
  - textual

  # linting
  - pre-commit
  - mypy

  # Testing
  - pytest
  - pytest-cov
  - pytest-asyncio
  - codecov
  - seabird
  - setuptools

  # Docs
  - sphinx>=7.0
  - myst-parser>=0.13
  - nbsphinx
  - ipykernel
  - pandoc
  - sphinx-copybutton
  # - sphinx-autodoc-typehints # https://github.com/OceanParcels/virtualship/pull/125#issuecomment-2668766302
  - pydata-sphinx-theme
  - sphinx-autobuild
